---
title: "git_00"
author: "Christina Jilavdaryan"
date: "Year 2020"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  
  
“Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

The Rowing Song  
Round the world and home again  
That's the sailor's way  
Faster faster, faster faster  
  
There's no earthly way of knowing  
Which direction we are going  
There's no knowing where we're rowing  
Or which way the river's flowing  
  
Is it raining, is it snowing  
Is a hurricane a–blowing  
  
Not a speck of light is showing  
So the danger must be growing  
Are the fires of Hell a–glowing  
Is the grisly reaper mowing  
  
Yes, the danger must be growing  
For the rowers keep on rowing  
And they're certainly not showing  
Any signs that they are slowing.  
  
